bug(api): handle branch names with slashes in them
cafkafk/rime pull request #21
Opened 2023-10-30 20:11 UTC by algernon

When dealing with branches, don't capture just one slice of the path as the branch name, but every part of the path from that point on. This lets us easily deal with branches that have slashes in their names.

Since the branch is always the last part of the URI, and the `/b/` or `/branch/` part routes things here anyway, capturing the rest of the path is safe. Only the path is captured, query strings are not, those aren't part of the routing.

Fixes #19.

2023-10-31 05:35 UTC, cafkafk commented
(love the name of this branch)

2023-10-31 05:37 UTC, cafkafk requested changes
This doesn't seem to work with gitlab for some reason (or I might have messed up the test)

2023-10-31 12:38 UTC, cafkafk commented
> > This doesn't seem to work with gitlab for some reason (or I might have messed up the test)
> 
> If you're testing with [this monstrosity](https://gitlab.com/cafkafk/hello/-/tree/a-/t/e/s/t/i/n/g/b/r/a/n/c/h-th@t-should-be-/ha/rd/to/d/e/a/l/wi/th?ref_type=heads), then I think the `@` confuses Nix. Rime's redirect is correct, it is the same URL as the one on the GitLab UI - Nix fails with both. The @ is probably treated as a HTTP basic auth separator.

I mean it works if I comment out gitlab
```diff
diff --git a/justfile b/justfile
index 0f736ad..9ea0258 100644
--- a/justfile
+++ b/justfile
@@ -204,7 +204,7 @@ itest:
 
     just run_test "http://localhost:3000/v1/codeberg/cafkafk/hello/b/a-/t/e/s/t/i/n/g/b/r/a/n/c/h-th@t-should-be-/ha/rd/to/d/e/a/l/wi/th.tar.gz"
     just run_test "http://localhost:3000/v1/github/cafkafk/hello/b/a-/t/e/s/t/i/n/g/b/r/a/n/c/h-th@t-should-be-/ha/rd/to/d/e/a/l/wi/th.tar.gz"
-    just run_test "http://localhost:3000/v1/gitlab/gitlab.com/cafkafk/hello/b/a-/t/e/s/t/i/n/g/b/r/a/n/c/h-th@t-should-be-/ha/rd/to/d/e/a/l/wi/th.tar.gz"
+    #just run_test "http://localhost:3000/v1/gitlab/gitlab.com/cafkafk/hello/b/a-/t/e/s/t/i/n/g/b/r/a/n/c/h-th@t-should-be-/ha/rd/to/d/e/a/l/wi/th.tar.gz"
     just run_test "http://localhost:3000/v1/forgejo/next.forgejo.org/cafkafk/hello/b/a-/t/e/s/t/i/n/g/b/r/a/n/c/h-th@t-should-be-/ha/rd/to/d/e/a/l/wi/th.tar.gz"
     just run_test "http://localhost:3000/v1/git.madhouse-project.org/cafkafk/hello/b/a-/t/e/s/t/i/n/g/b/r/a/n/c/h-th@t-should-be-/ha/rd/to/d/e/a/l/wi/th.tar.gz"
```

This might be a gitlab'ism?

2023-10-31 12:51 UTC, algernon commented
Possibly, yeah. Can you maybe try a branch name *with* `@`, but without any `/` (I don't have an account on any gitlab server)?

2023-10-31 12:57 UTC, algernon commented
Oh. This *is* a bug in Rime! I'm just blind.

Compare:

- URL from GitLab web UI: `https://gitlab.com/cafkafk/hello/-/archive/a-/t/e/s/t/i/n/g/b/r/a/n/c/h-th@t-should-be-/ha/rd/to/d/e/a/l/wi/th/hello-a--t-e-s-t-i-n-g-b-r-a-n-c-h-th@t-should-be--ha-rd-to-d-e-a-l-wi-th.tar.gz`
- URL from Rime: `https://gitlab.com/cafkafk/hello/-/archive/a-/t/e/s/t/i/n/g/b/r/a/n/c/h-th@t-should-be-/ha/rd/to/d/e/a/l/wi/th/hello-a-/t/e/s/t/i/n/g/b/r/a/n/c/h-th@t-should-be-/ha/rd/to/d/e/a/l/wi/th.tar.gz`

We need to turn some of the `/`s into `-`s. As in, this is the format string we use:

```
        let uri = format!(
            "https://{}/{}/{}/-/archive/{}/{}-{}.tar.gz",
            host, user, repo, git_ref_name, repo, git_ref_name,
        );
```

The second `git_ref_name` needs a `/`->`-` treatment. This is not a new bug in this PR, this just brings it to the surface.

2023-10-31 12:59 UTC, algernon commented
I'll update this PR to fix the bug too. Might take a couple of hours to find some uninterrupted screentime.

2023-10-31 13:14 UTC, cafkafk commented
> I'll update this PR to fix the bug too. Might take a couple of hours to find some uninterrupted screentime.

nw, take whatever time you need!

2023-11-01 14:33 UTC, cafkafk approved these changes
Nice, that fixed it! `nix flake check` and `just itests` also work, looks good!

2023-11-01 14:34 UTC, merged