feat(semver): Semver locking API endpoint
cafkafk/rime pull request #31
Opened 2023-11-01 20:33 UTC by algernon

I'm sorry, this is another stacked pull request, built on top of #30 this time. The gist of it is in ca1aad3ed898458e3a83e8c7f63ff5a6e896b6e9, and the commit message explains it well enough, I believe:

---

This adds a new `/semver/:version` (and `/s/:version`) route to all forges that implement release listing. The specified version is parsed as a semver version requirement (more about that here[^1]), and releases for the given repo are matched against it.

The matching is done by comparing the sanitized tag name: if the tag begins with `v`, that character is stripped, and the rest is parsed as a semantic version string; if the tag begins with the repo name and a dash (another common pattern in tagging), then the `{repo}-` prefix is removed, and the rest is parsed as a semantic version string; if neither case applies, we try to parse the tag name as a semantic version as is.

If we can't parse the sanitized tag name as a semantic version, then we consider it non-matching. Otherwise it is compared to the given version requirement.

This allows many forms of version requirement specifications, but is limited. Another way will be added later that allows specifying more complex ranges in the query string.

 [^1]: https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html

Fixes #10.

---

I opted to build this on top of #30, because otherwise there would have been tremendous amounts of code duplication. There's still more than I'd like, but *considerably* less than it would've been otherwise.

I'll be pushing another commit soonish, which will make it possible to specify more complex semver version requirements via a query string, rather than as a path. It won't do any fundamental changes, and that will call the same underlying functions. The difference is only in where the version requirement is coming from.

2023-11-02 00:06 UTC, algernon commented
I *think* I am pretty happy with how this ended up. Leaving it in Draft status until #30 is dealt with, however.

2023-11-03 16:55 UTC, cafkafk reviewed
let's get in #36 and #35 first, then dunno if you prefer this or #37 after

2023-11-03 17:57 UTC, algernon commented
#37, because I have a few improvements to do here.

2023-11-03 18:18 UTC, algernon commented
Rebased on main, and it's now ready for review, I fixed the remaining issue I had in mind.

2023-11-03 18:37 UTC, cafkafk requested changes
could you add some simple integration tests for this, like has been done before in the `justfile`?

2023-11-03 18:47 UTC, algernon commented
Yep! Give me a few, and I'll add some.

2023-11-03 19:20 UTC, algernon commented
Three tests added:

- The first tests that the `/s/*.tar.gz` endpoint works, and resolves to a proper release.
- The second tests that `/s/0.0.2-pre.1.tar.gz` resolves to a pre-release.
- The third tests that `/s/*.tar.gz?version=>=0.0.1,<=0.0.2-pre.5` ignores the `*`, and uses the version requirement in the query string, which resolves to a pre-release.

All three test against `/github/cafkafk/hello`, because that had a flake, and suitable releases to test with. I'm happy to check out the others, and add more, but this tests the core functionality.

2023-11-04 06:19 UTC, cafkafk approved these changes
Looks good, thanks for adding tests. It's sad that we need to encode `?version=%3e%3d0.0.1%2c%3c%3d0.0.2-pre.5`, but I guess there's no way to avoid that. 

Anyways, this is a major feature, really cool to see it land, thanks!

2023-11-04 06:20 UTC, cafkafk commented
> I'm happy to check out the others, and add more, but this tests the core functionality.

Yea I think it's fine, at least for now IMO

2023-11-04 06:20 UTC, merged