feat(flakehub): Add support for release-based endpoints
cafkafk/rime pull request #38
Opened 2023-11-03 18:45 UTC by algernon

This series (built on top of #31, out of convenience) teaches the FlakeHub forge how to grab a list of releases for a particular project. It does so by doing some minor refactoring in the Forge trait, and adjusting two handlers accordingly - the refactoring allows implementors of the trait to override how releases are fetched, so that `FlakeHub` can supply its own method (because the API, and its response is wildly different from the default format supported by `ForgeReleases`).

With the trait & handlers adjusted, `FlakeHub` can implement the `get_api_releases_url()` and `get_releases()` functions, which in turn makes the `/v1/flakehub/:user/:repo.tar.gz` and the semver endpoints work.

Our `FlakeHub` struct fetches the release list by hitting `https://api.flakehub.com/version/resolve/:user/:repo/*`, which returns all versions that match the version requirement (`*`). We then sort those versions, because `ForgeReleases` assumes a sorted list, and voila, we're done!

This lets us hit `/v1/flakehub/nixos/nixpkgs.tar.gz` to get the latest (stable) release, and `/v1/flakehub/nixos/nixpkgs/s/0.1.tar.gz` to get the latest unstable one.

Fixes #32.

2023-11-03 18:46 UTC, algernon commented
Draft, for now, because I'll likely need to rebase it later. There will be a followup to this, too: one that makes Flakehub's semver endpoint much more efficient, and the `/v/` and `/t/` endpoints too. But those are independent changes, and I still need to iterate on them a little, so will be submitted separately.

2023-11-04 08:26 UTC, algernon commented
Rebased on top of main, and added an integration test

2023-11-04 08:46 UTC, algernon commented
While testing this, I identified blocking issues, like not supporting pre-releases at all. The downside of querying releases via `api.flakehub.com/version/resolve/:user/:repo/*` is that `*` does not match pre-releases.

However, there are other ways to solve the issue, without having to use the `api.flakehub.com/f/:user/:repo/releases` endpoint! We can just delegate the whole "find the latest version" and "resolve a semver" task to flakehub itself, because it supports both out of the box anyway.

2023-11-04 09:46 UTC, algernon commented
Allright! Rewrote the whole thing, now it delegates both the `/:user/:repo.tar.gz` and `/:user/:repo/semver/:version.tar.gz` endpoints to FlakeHub.

I added three integration tests: one to test the `/:user/:repo.tar.gz` endpoint (which should return the latest proper release), one to test that `/:user/:repo/s/:version` can return a pre-release, and a third that `/s/*.tar.gz` is still a proper non-pre release.

2023-11-04 12:41 UTC, cafkafk requested changes
I'm not sure why, but I'm getting this when running integration tests:

```
warning: error: unable to download 'http://localhost:3000/v1/gitlab.com/cafkafk/hello.tar.gz': HTTP error 400

       response body:

       failed to auto-detect the forge on gitlab.com; using cached version
```

I'm not sure what (if anything) here caused this.

2023-11-04 12:42 UTC, cafkafk commented
I'm also getting this on main

2023-11-04 12:47 UTC, cafkafk approved these changes
LGTM, dunno how I've managed to overlooked a broken test on main >_<

2023-11-04 12:48 UTC, merged