An auto-discovery implementation
cafkafk/rime pull request #5
Opened 2023-10-28 20:29 UTC by algernon

This builds on top of #2, and is a draft, as there are a number of ways to approach the implementation, and this is but one of them. The goal here is for `/v1/:host` to do an auto-discovery, if `:host` was not recognised as a forge by the other routes.

The implementation I chose is on the verbose side, because I wanted to delegate the discovery itself to `api::v1::<forge>::is_<forge>`, so that the auto discovery endpoint is a relatively thin wrapper around those. *Where* rime redirects to, however, I kept that in the auto discovery endpoint, but can easily delegate that to the forge endpoints themselves, too.

I chose to use a pattern like `AutoDiscovery::new_for(&host).try_github().await.expect("...").try_flakehub().await.expect("...").url(&url)`, because... I dunno. I found this nice flat chain nicer than an if/else soup. The if/else soup would be less code, however, so if you think that's the nicer approach, I'll go and do that.

The implementation itself is in the [third commit](https://github.com/algernon/rime/commit/e05462fe178253b92d10d4039f0629bf088853f7).

2023-10-29 09:43 UTC, cafkafk requested changes
I know this is in draft status, but can you base this on main? I'd like to take a look at it

2023-10-29 10:05 UTC, algernon commented
Yep, I can! Done.

2023-10-29 10:09 UTC, algernon commented
As an additional note: I left the github & flakehub auto-discovery as-is (they simply compare the host to github.com/flakehub.com, respectively), even though the main app could just mount the appropriate routes at those locations. The reason I left them as-is, is to (eventually) support GitHub EE and self-hosted flakehub (if there's such a thing?). However, that may be rather pointless, and a lot of unnecessary code, so I'm thinking about removing that, and just adding two extra routes instead.

2023-10-29 10:15 UTC, cafkafk commented
> self-hosted flakehub (if there's such a thing?)

Not for now I think... but might be a thing later? They did talk about a private flake feature :woman_shrugging:

2023-10-29 10:49 UTC, algernon commented
> I'll take a look at it soon, I mean, having the code be easily extensible is a plus.

It'd be extensible even if I removed the github/flakehub auto-discovery for now: they use the same pattern as forgejo, so it's just a bit of copy pasta to add it back, if/when the need arises. But it's equally easy to just keep it. I'll defer that decision to you! =)

2023-10-30 07:52 UTC, cafkafk commented
> > I'll take a look at it soon, I mean, having the code be easily extensible is a plus.
> 
> It'd be extensible even if I removed the github/flakehub auto-discovery for now: they use the same pattern as forgejo, so it's just a bit of copy pasta to add it back, if/when the need arises. But it's equally easy to just keep it. I'll defer that decision to you! =)

I mean I suppose we should default to avoiding doing unnecessary computation :woman_shrugging:, after reviewing the code, I'm fine with removing them in favor of directly routing tbh

2023-10-30 07:56 UTC, cafkafk commented
Also in case I forget myself I did review the code and it looks good, I just haven't tested it yet (I will before merge).

Do you wanna add gitlab support before a merge? You don't have to of course (and it could always be done in a follow up PR if you prefer that).

2023-10-30 08:57 UTC, algernon commented
I can add GitLab, yep (I've done so locally, just haven't pushed it yet, because I wanted to do some testing first). Will change it to do direct routing for github.com/flakehub.com, too.

2023-10-30 09:32 UTC, algernon commented
Rebased on main, added GitLab auto-discovery, and changed github.com and flakehub.com to use direct routing instead.

The GitLab auto-discovery appears to work for gitlab.com itself, too. I *could* add a redirect like there is one for Codeberg, to avoid having to a discovery. But gitlab.com being behind a login wall... I don't feel like it, really. It still works, it's just a tiny bit slower, having to do the auto-detection.

2023-10-30 13:41 UTC, cafkafk approved these changes
Looking at this now, this is actually a really nice feature, shaving off a whole path parameter is great UX. I added some tests to ensure we don't later introduce regressions (or to make us aware of changes to any source forge that break rime).

Good work, thanks for all the contributions so far, they really add some value to rime!

2023-10-30 13:43 UTC, cafkafk commented
My plan was to release on every thursday like I do for other software I maintain, but I kinda really want this for my personal use on rime.cx already, specially with all the forges and auto discovery... so maybe I'll cut a release after merging this and deploy it today...

2023-10-30 13:44 UTC, merged